More Cleanup
SCUACM/ACM-Website pull request #36
Opened 2023-06-01 01:49 UTC by walkerselby

Cleaned a lot of stuff up
Upgraded dependency to prevent XSS
See commits for more info

2023-06-01 04:28 UTC, jordanmosakowski requested changes

2023-06-01 04:28 UTC, jordanmosakowski commented on functions/index.js
> +        const doc = element;
Can we just do `for(const doc of wokshop.docs)` which then eliminates the 2nd line?

2023-06-01 04:28 UTC, jordanmosakowski commented on src/layout/Navbar.vue
> +import {auth, db} from '@/firebase';
We keep the local file (..) so we can switch over to using the firebase emulators easier. Working on a PR that details that better bc rn we just change a line manually and then remove it before we commit lol

2023-06-01 23:11 UTC, rileywong311 approved these changes

2023-06-02 00:51 UTC, jordanmosakowski approved these changes

2023-06-02 05:15 UTC, merged